#!/bin/bash
# Show help
show_help() {
   cat <<EOF
Usage: ./deploy [-e] [-p] [-h]
   -e   ember environment to build
   -p   project to deploy to (default = production)
   -h   displays basic help
EOF
}

# A POSIX variable
OPTIND=1

# Initialize our own variables:
environment="development"
project="staging"

while getopts "h?e:p:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    e)  environment=$OPTARG
        ;;
    p)  project=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

ember build --environment=$environment
firebase deploy -P $project
